### ISSUE TITLE
Auto-detect user language

### ISSUE THREAD

**Issue by bucanero** [cy33hc/ps4-ftp-client#1]
Hello,

I saw that the user needs to manually edit the `.ini` file to set the language, so perhaps you can just auto-detect the current user selected language, like this:

```c
int32_t language;

ret = sceSystemServiceParamGetInt( ORBIS_SYSTEM_SERVICE_PARAM_ID_LANG, &language );
```

Since you're using Open Orbis, the support for this method and values is already there. (check `include/orbis/_types/sys_service.h`)

I hope it helps, cheers

**Comment by cy33hc** [comment]
@bucanero Thx for the info. I updated the app to auto detect the system language. For the non standard languages, user will still need to update the config file manually.
